### Kategori
GET http://localhost:5000/kategoris

###
GET http://localhost:5000/kategoris/6300385d18aa7a7fdc6f0e34

###
GET http://localhost:5000/kategoriByJenis/Buku

###
POST http://localhost:5000/kategoris
Content-Type: application/json

{
    "jenisKategori": "Buku",
    "namaKategori": "Hukum"
}

###
PATCH http://localhost:5000/kategoris/6300387718aa7a7fdc6f0e37
Content-Type: application/json

{
    "jenisKategori": "Buku",
    "namaKategori": "Hukum"
}

###
DELETE http://localhost:5000/kategoris/6300387718aa7a7fdc6f0e37

### Sub Kategori
GET http://localhost:5000/subKategoris

###
GET http://localhost:5000/subKategoris/63004e6829377081911162b3

###
GET http://localhost:5000/subKategoriByKategori/6300385d18aa7a7fdc6f0e34

###
POST http://localhost:5000/subKategoris
Content-Type: application/json

{
    "kategoriId": "6300385d18aa7a7fdc6f0e34",
    "namaSubKategori": "Buku Desain Rumah"
}

###
PATCH http://localhost:5000/subKategoris/63004e8f29377081911162b8
Content-Type: application/json

{
    "kategoriId": "6300385d18aa7a7fdc6f0e34",
    "namaSubKategori": "Buku Desain Rumah"
}

###
DELETE http://localhost:5000/subKategoris/63004e8f29377081911162b8

### Produk
GET http://localhost:5000/produks

###
GET http://localhost:5000/produks/63004e6829377081911162b3

###
GET http://localhost:5000/produkBySubKategori/63004e6829377081911162b3

###
POST http://localhost:5000/produks
Content-Type: application/json

{
    "subKategoriId": "63004e6829377081911162b3",
    "namaProduk": "Buku Dekorasi 2",
    "hargaProduk": 2000,
    "hargaDiskonProduk": 1900,
    "deksripsi": "Buku Dekorasi 2 Deskripsi",
    "totalBintangProduk": 4.7
}

###
PATCH http://localhost:5000/produks/6300514c0e83b165d25f54b6
Content-Type: application/json

{
    "subKategoriId": "63004e6829377081911162b3",
    "namaProduk": "Buku Dekorasi 2",
    "hargaProduk": 2000,
    "hargaDiskonProduk": 900,
    "deksripsi": "Buku Dekorasi Deskripsi",
    "totalBintangProduk": 4.8
}

###
DELETE http://localhost:5000/produks/630051d50e83b165d25f54ca